version: "3.9"

services:

  db:
    container_name: postgres_db
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - ./.env

  web:
    container_name: FastAPI_web
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./static/:/static
      - ./media/:/media
      - ./:/app
    entrypoint: ./wsgi-entrypoint.sh
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - db


volumes:
  postgres_data:
  media:
  static:

networks:
  my-network:
