"""change datetime

Revision ID: 38327310accd
Revises: 66694a72f2a7
Create Date: 2022-12-25 15:05:58.234989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38327310accd'
down_revision = '66694a72f2a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
