"""change datetime

Revision ID: 66694a72f2a7
Revises: d56fe57b1b05
Create Date: 2022-12-25 14:47:56.196524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66694a72f2a7'
down_revision = 'd56fe57b1b05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
